### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Dark patches on the edges of the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#325]
## Observed behaviour

There are dark patches on the edges of the map.

## Expected behavior

No dark patches.

## Screenshots

![shot_20230929_081207_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ef183671-602f-4d04-afc3-59d89bcb7620)

![shot_20230929_081217_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3b253ed3-26ab-4dc3-82f1-622cd0eed46e)

![shot_20230929_081233_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b7abb08a-f4eb-4496-8c77-6a198314ded0)

![shot_20230929_081253_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8828060a-ef55-475a-baa7-11168f0ee232)

![shot_20230929_081748_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/70b72cb3-6dea-4c14-a23e-932756572bf9)

**Comment by NoMerciBKK** [comment]
fixed can be closed

**Comment by xezon** [comment]
Is still visible.

**Comment by NoMerciBKK** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/c6f15829-ea17-46e9-8abc-ee4ee126bd15)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/cc60b8ea-9015-402e-80e4-9f204d307931)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/13906121-12c2-49a6-a040-475b67436b1a)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/e658d0d0-15a1-43d3-8b53-37e2216bed98)

**Comment by DoMiNaToRuk2** [comment]
xezon is this fixed?

**Comment by xezon** [comment]
The last version I received (the one added here in GitHub) had it improved, but not entirely fixed. This report is very minor, but should be fixable by applying uniform terrain texture at all edges of map.

**Comment by NoMerciBKK** [comment]
> The last version I received (the one added here in GitHub) had it improved, but not entirely fixed. This report is very minor, but should be fixable by applying uniform terrain texture at all edges of map.

as you can see on my screenshots above there are non at my screen so if some are left i d need at least to know where they are to be able to fix it otherwise i d keep it as it is rgn @xezon

**Comment by xezon** [comment]
Looks good to me. There are still a few tiny artifacts, but barely visible.

![shot_20231117_183717_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1191db43-d2c4-4cdc-a95b-1083658b34e1)

![shot_20231117_183745_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/080d0d6d-253c-4595-8f7e-793e64199c42)
